### PR TITLE
adding position of block + semi-optimized batch blocks

### PR DESCRIPTION
**Pull request by HansBhatia**
Added function getBlocks to add all blocks within a range given a specified interval in seconds.
Added 'position' parameters to block functions so a user can specify if they desire an earlier or later block timestamp.

### CODE REVIEW

**Comment by kai-thompson** [comment]
This PR looks great. I'm gonna give it an in-depth review after work today. Do you attend UW CS?

**Comment by HansBhatia** [comment]
Hey Kai, I am still in the Uw cs program.

**Comment by kai-thompson** [comment]
> Hey Kai, I am still in the Uw cs program.

That's awesome; I have some friends there. I sent you an invite on LinkedIn!

Anyways, I'll get some unit tests for this tomorrow and get this PR merged.

**Comment by kai-thompson** [comment]
> > Hey Kai, I am still in the Uw cs program.
> 
> That's awesome; I have some friends there. I sent you an invite on LinkedIn!
> 
> Anyways, I'll get some unit tests for this tomorrow and get this PR merged.

Hey Hans, I wasn't able to push to a new branch in your forked repo so I pushed my review/changes to [this](https://github.com/kai-thompson/eth-date-to-block/tree/block-position-batch-blocks) branch. Feel free to open a PR with that branch whenever you're ready!

**Pull request closed without merging**
